version: '3'
services:
  wiremock:
    image: rodolpheche/wiremock:2.25.1
    volumes:
      - ./src/test-integration/resources/wiremock:/home/wiremock
    ports:
      - 9000:8080
  app:
    image: adoptopenjdk/openjdk11:jdk-11.0.5_10-alpine
    volumes:
      - ./build/libs:/opt/app:ro
    command: java '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008' -jar /opt/app/albums-browser-0.0.1-SNAPSHOT.jar
    ports:
      - 5008:5008
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: component-test
    depends_on:
      - wiremock